### ISSUE TITLE
Unexpected behaviour with DSMC ionisation

### ISSUE THREAD

**Issue by peterparsons2** [ECP-WarpX/WarpX#6411]
I am simulating a ~MeV proton beam propagating through a gas including ionisation with DSMC. The proton beam appears to lose almost all of its foward velocity when ionisation occurs. The bimodal distribution of v_z suggests that the protons are losing the momentum in one single ionisation event - I would have expected the loss in foward momentum to be much smaller. There are no unexpected effects on momentum in the x and y directions and if the collisions are turned off v_z does not decrease unexpectedly. Below are histograms of v_z of the proton beam at three timesteps.

<img width="328" height="598" alt="Image" src="https://github.com/user-attachments/assets/36a2bbc5-b55d-4a03-9966-60765bc28538" />

Here is the collision definition in my input file:

```
collisions.collision_names = proton_impact_ionisation 

proton_impact_ionisation.type 							= dsmc
proton_impact_ionisation.scattering_processes 			= ionization
proton_impact_ionisation.species 						= protons bg_nitrogen
proton_impact_ionisation.ionization_target_species 		= bg_nitrogen
proton_impact_ionisation.product_species 				= electrons N_plus
proton_impact_ionisation.ionization_cross_section 		= [path to cross section file]
proton_impact_ionisation.ionization_energy 				= 15.581
```

Also, currently ionised electrons are given a roughly isotropic momentum distribution, wheras in the case of a fairly high energy beam into a gas, the resulting electron momentum should be foward peaked. Maybe this could be considered as a future improvement?

Many thanks

**Comment by peterparsons2** [comment]
An update on this - it appears total energy is not being conserved. Using reflecting particle boundaries, here is the total particle energy with time:

<img width="730" height="457" alt="Image" src="https://github.com/user-attachments/assets/3333d6f4-90a4-457c-a6ac-094432949e6d" />

If collisions are turned off, energy is conserved.

**Comment by RemiLehe** [comment]
Thanks for reporting this @peterparsons2. Could you post a full input script to reproduce the above issue?

I think that this unphysical issue might be caused by the assumptions of the physical model for impact ionization in WarpX. The code for the distribution of energy among the products after an impact ionization event was originally written with electron impact ionization in mind in WarpX, and it can be found here:
https://github.com/BLAST-WarpX/warpx/blob/development/Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H#L411

In the past I have seen this resulting in a similar effect as the one you are showing when applied to ions. As a temporary solution, I have implemented a naive alternative distribution of energy here:
https://github.com/BLAST-WarpX/warpx/pull/5868/files
Feel free to try that one in your simulation.

However, in the longer term, we should provide different known models from the literature. I think that @roelof-groenewald briefly started to look into this. @peterparsons2 Are you yourself aware of any widely-used physical models for the distribution of energy between products?

**Comment by RemiLehe** [comment]
Regarding the loss of conservation of energy: this is not expected, but maybe the electrons have high velocity and quickly exit the box here, thereby accounting for the loss of energy?

**Comment by peterparsons2** [comment]
Thanks for the response. Here is a simplified version of the input file, but still reproduces the same effect: [intn_s03.txt](https://github.com/user-attachments/files/23827610/intn_s03.txt)

Here's the cross-section file: [crosssection.txt](https://github.com/user-attachments/files/23789672/crosssection.txt)

A good reference for collisional ionisation is Stephen DiIorio's thesis, who implemented ion impact ionisation in Osiris: https://deepblue.lib.umich.edu/items/c799120e-7d66-4e75-8564-d30bd76c2fa6 . Collisional ionisation differential cross-sections with respect to the ionised electron energy are discussed in section 2.3.

Regarding the energy loss, the plot above is from a simulation run with reflecting particle boundaries, and the macroparticle numbers do not decrease - I don't think electrons are leaving the box. There is only a small (~10 J) increase in field energy, so it's not that either.

I'll run my simulation with your alternative ionisation method and I'll let you know if the results are different

Many thanks!

**Comment by peterparsons2** [comment]
Hi - I've ran my inputs with your alternative distribution, and it appears to have fixed the issues - both with the unexpected reducton in momentum and with the non-conserved energy. Thanks very much for your help!
